### ISSUE TITLE
Notice that two persistent volumes get created for each pod on AWS.

### ISSUE THREAD

**Issue by nevosial** [humio/humio-operator#160] opened 2020-09-30 09:05 UTC
Humio cluster spec uses gp2 storage class defined.
```
....
  dataVolumePersistentVolumeClaimSpecTemplate:
    storageClassName: gp2
    accessModes: [ReadWriteOnce]
    resources:
      requests:
        storage: 500Gi
...
```

AWS EKS version: 1.17

EBS driver plugin version:
`amazon/aws-ebs-csi-driver:v0.4.0`

Storage Class on the cluster.
```
NAME            PROVISIONER             RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
cloud-storage   ebs.csi.aws.com         Delete          WaitForFirstConsumer   true                   36d
gp2 (default)   kubernetes.io/aws-ebs   Delete          WaitForFirstConsumer   false                  48d
```

When the humio pod is spinning up; it creates 2 volumes on the AWS console with the name kubernetes-dynamic-pvc-d4a79a5f-dc0b-40af-b903-04e9fc2d84cf; However, only one is in the 'In-use' status and the other one is always in the 'Available' status as seen in AWS. The pods then goes into a `CrashLoopBackOff` due to a FailedAttachVolume warning or in some cases 1 out of 3 pods are always stuck in the Init phase.

```
ubuntu@ip-10-150-1-220:/tmp/humio-operator/oauth$ kch
portal-humio-core-alpnzq                            1/2     CrashLoopBackOff   6          12m
humio-operator-5559ddb85-nzcql                         1/1     Running            0          6h2m
```

```
48s         Normal    Provisioning             persistentvolumeclaim/portal-humio-core-gtydvy   External provisioner is provisioning volume for claim "cloudops/portal-humio-core-gtydvy"
48s         Normal    WaitForFirstConsumer     persistentvolumeclaim/portal-humio-core-gtydvy   waiting for first consumer to be created before binding
14s         Normal    WaitForFirstConsumer     persistentvolumeclaim/portal-humio-core-lgxuum   waiting for first consumer to be created before binding
14s         Normal    WaitForFirstConsumer     persistentvolumeclaim/portal-humio-core-nwmjpk   waiting for first consumer to be created before binding
43s         Normal    ProvisioningSucceeded    persistentvolumeclaim/portal-humio-core-gtydvy   Successfully provisioned volume pvc-d4a79a5f-dc0b-40af-b903-04e9fc2d84cf using kubernetes.io/aws-ebs
3m34s       Normal    Scheduled                pod/portal-humio-core-alpnzq                     Successfully assigned cloudops/portal-humio-core-alpnzq to ip-10-150-12-138.us-west-2.compute.internal
3m29s       Normal    SuccessfulAttachVolume   pod/portal-humio-core-alpnzq                     AttachVolume.Attach succeeded for volume "pvc-d4a79a5f-dc0b-40af-b903-04e9fc2d84cf"
3m6s        Normal    Started                  pod/portal-humio-core-alpnzq                     Started container zookeeper-prefix
3m6s        Normal    Created                  pod/portal-humio-core-alpnzq                     Created container zookeeper-prefix
3m6s        Normal    Pulled                   pod/portal-humio-core-alpnzq                     Container image "humio/humio-operator-helper:0.0.7" already present on machine
3m4s        Normal    Started                  pod/portal-humio-core-alpnzq                     Started container auth
70s         Normal    Created                  pod/portal-humio-core-alpnzq                     Created container humio
70s         Normal    Started                  pod/portal-humio-core-alpnzq                     Started container humio
70s         Normal    Pulled                   pod/portal-humio-core-alpnzq                     Container image "humio/humio-core:1.13.4" already present on machine
3m4s        Normal    Created                  pod/portal-humio-core-alpnzq                     Created container auth
3m4s        Normal    Pulled                   pod/portal-humio-core-alpnzq                     Container image "humio/humio-operator-helper:0.0.7" already present on machine
51s         Warning   FailedAttachVolume       pod/portal-humio-core-alpnzq                     AttachVolume.Attach failed for volume "pvc-d4a79a5f-dc0b-40af-b903-04e9fc2d84cf" : volume is still being detached from the node
44s         Warning   BackOff                  pod/portal-humio-core-alpnzq                     Back-off restarting failed container
```

The auth container logs 

```
ubuntu@ip-10-150-1-220:/tmp/humio-operator/oauth$ kc logs portal-humio-core-alpnzq -c auth
Starting humio-operator-helper version 0.0.7
waiting on files /data/humio-data/local-admin-token.txt, /data/humio-data/global-data-snapshot.json
waiting on files /data/humio-data/local-admin-token.txt, /data/humio-data/global-data-snapshot.json
waiting on files /data/humio-data/local-admin-token.txt, /data/humio-data/global-data-snapshot.json
```

**Comment by jswoods** [comment] 2020-09-30 23:45
I have not been able to reproduce this. What's not clear to me is how csi is relevant here since you're creating a cluster with the gp2 storage dirver. 

Can you confirm which ebs provisioner you are using?
Do you have any other humiocluster resources?

To try to reproduce, I created a 1.17 EKS cluster with the v0.4.0 version of the csi driver and Humio clusters with both: `storageClassName: ebs-sc` as well as `storageClassName: gp2`. Both clusters provisioned correctly and did not have any duplicate ebs volumes in AWS.

Storage classes:
```
$ kubectl get storageclass
NAME            PROVISIONER             RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
ebs-sc          ebs.csi.aws.com         Delete          WaitForFirstConsumer   false                  13m
gp2 (default)   kubernetes.io/aws-ebs   Delete          WaitForFirstConsumer   false                  2d
```

Using gp2:
```
$ kubectl get pods,pvc -n logging -l app.kubernetes.io/instance=humio-storage-testing-pvc
NAME                                   READY   STATUS    RESTARTS   AGE
pod/humio-storage-testing-pvc-core-etgnee   2/2     Running   0          10m
pod/humio-storage-testing-pvc-core-rrbjug   2/2     Running   0          83s
pod/humio-storage-testing-pvc-core-zyvjfo   2/2     Running   0          38m

NAME                                                     STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
persistentvolumeclaim/humio-storage-testing-pvc-core-cjbwpv   Bound    pvc-3144d215-dc97-4285-a34d-b8f27dd9d1b7   10Gi       RWO            gp2            83s
persistentvolumeclaim/humio-storage-testing-pvc-core-ewoins   Bound    pvc-07fd5ac8-da3e-4da4-902c-2dfb0cadc891   10Gi       RWO            gp2            38m
persistentvolumeclaim/humio-storage-testing-pvc-core-mbthit   Bound    pvc-4b2ee5d2-508e-4b2b-9e47-178ace46500d   10Gi       RWO            gp2            38m
```

Using ebs-sc:
```
# kubectl get pods,pvc -n logging -l app.kubernetes.io/instance=humio-storage-testing-pvc-csi
NAME                                       READY   STATUS    RESTARTS   AGE
pod/humio-storage-testing-pvc-csi-core-dbjpxi   2/2     Running   0          6m29s
pod/humio-storage-testing-pvc-csi-core-laxbwy   2/2     Running   0          4m54s
pod/humio-storage-testing-pvc-csi-core-mghiao   2/2     Running   0          5m44s

NAME                                                         STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
persistentvolumeclaim/humio-storage-testing-pvc-csi-core-jvtfjt   Bound    pvc-b042b72d-dd57-4d97-90d5-c82bdf40bd90   10Gi       RWO            ebs-sc         6m29s
persistentvolumeclaim/humio-storage-testing-pvc-csi-core-podlce   Bound    pvc-54f2b5a8-1645-48d8-a18e-429d3a5844e3   10Gi       RWO            ebs-sc         6m29s
persistentvolumeclaim/humio-storage-testing-pvc-csi-core-utdtuh   Bound    pvc-b4057038-fc46-4bdf-a280-6d0029ca6017   10Gi       RWO            ebs-sc         6m29s
```

Perhaps you can send the output of:
```
kubectl get humiocluster -A
kubectl get pods,pvc -A -l app.kubernetes.io/managed-by=humio-operator
kubectl get storageclass
```

Unless there is something specific triggering this behavior I'm not sure what else to test. If it is possible it may be worth testing in a fresh EKS cluster with the default storage provider.

**Comment by nevosial** [comment] 2020-10-01 19:39
Thanks Jestin,

Here is the output from 

```
ubuntu@ip-10-150-1-220:~$ kc get humiocluster -A
NAMESPACE   NAME              STATE     NODES   VERSION
cloudops    ccsportal-humio   Running   3       1.13.4--build-196036911--sha-87097bb54d33caf1a342f7c435157e35e027ddf3
```

```
ubuntu@ip-10-150-1-220:~$ kc get pods,pvc -A -l app.kubernetes.io/managed-by=humio-operator
NAMESPACE   NAME                              READY   STATUS     RESTARTS   AGE
cloudops    pod/portal-humio-core-sfeiva   2/2     Running    0          10h
cloudops    pod/portal-humio-core-wbsexh   2/2     Running    0          10h
cloudops    pod/portal-humio-core-yrpqlf   0/2     Init:0/1   0          10h

NAMESPACE   NAME                                                STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
cloudops    persistentvolumeclaim/portal-humio-core-cwaonr   Bound    pvc-ced8735c-29d5-4772-b194-d76fb280a836   500Gi      RWO            gp2            33h
cloudops    persistentvolumeclaim/portal-humio-core-paroyt   Bound    pvc-199e2678-1a54-485a-800e-fede35513600   500Gi      RWO            gp2            33h
cloudops    persistentvolumeclaim/portal-humio-core-wfmwxs   Bound    pvc-647fea1c-b75c-4625-a738-8554aeb6143a   500Gi      RWO            gp2            33h
```

```
ubuntu@ip-10-150-1-220:~$ kubectl get sc
NAME            PROVISIONER             RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
cloud-storage   ebs.csi.aws.com         Delete          WaitForFirstConsumer   true                   37d
gp2 (default)   kubernetes.io/aws-ebs   Delete          WaitForFirstConsumer   false                  49d
```

If you notice one of the pods is still waiting in the Init phase; following is the describe from the pod.
```
Events:
  Type     Reason              Age                   From                                                  Message
  ----     ------              ----                  ----                                                  -------
  Warning  FailedMount         5m2s (x290 over 11h)  kubelet, ip-10-150-12-138.us-west-2.compute.internal  Unable to mount volumes for pod "portal-humio-core-yrpqlf_cloudops(5ed8ea4b-7f30-40cf-9985-1388d742b678)": timeout expired waiting for volumes to attach or mount for pod "cloudops"/"portal-humio-core-yrpqlf". list of unmounted volumes=[humio-data]. list of unattached volumes=[shared tmp humio-tmp init-service-account-secret auth-service-account-secret humio-data extra-kafka-configs role-permissions ccsportal-humio-humio-token-z525x]
  Warning  FailedAttachVolume  16s (x332 over 11h)   attachdetach-controller                               AttachVolume.Attach failed for volume "pvc-199e2678-1a54-485a-800e-fede35513600" : volume is still being detached from the node
```

On the AWS console i see two volumes one 'Available` and the other `In-use` when i search for `pvc-199e2678-1a54-485a-800e-fede35513600`

Also what is the total number of pv that get created on AWS in your test ? 
In my environment, I see 6 pvs getting created for humio ; with 3 in `Available` and the other 3 `In-use` with one pod getting stuck in the `Init` phase.

**Comment by jswoods** [comment] 2020-10-05 17:44
> Also what is the total number of pv that get created on AWS in your test ?

I had 3 pv's created.

> In my environment, I see 6 pvs getting created for humio ; with 3 in Available and the other 3 In-use with one pod getting stuck in the Init phase.

In your command output, I only see 3 pvcs. Can you include info about the other pvcs? I'd like to understand where the other pvc's are trying to attach.

**Comment by nevosial** [comment] 2020-10-29 23:15
we haven't seen this issue once we started using the csi provisioner. (`ebs.csi.aws.com`) instead of the `kubernetes.io/aws-ebs` for our storage class.

**Comment by SaaldjorMike** [comment] 2020-11-05 12:52
Thank you for the update. We have not been able to reproduce this, and given that you do not see the same behaviour with a different storage provisioner I believe this is not a bug in the humio-operator code base.

I'm closing this issue. If you stumble upon this again, especially if you have concrete steps for how to reproduce it that indicates a problem in this project, please let us know.

**Closed by SaaldjorMike** 2020-11-05 12:52 UTC
